# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

# [[main]]
#   name = "Состав кафедры"
#   url = "/people/"
#   weight = 20

# [[main]]
#   name = "Программы"
#   url = "/programs/"
#   weight = 30
#   identifier = "edu"

# [[menu]]
#   name = "Бакалавриат"
#   url = "/programs/bachelor/"
#   parent = "edu" 

# [[main]]
#   name = "Новости"
#   url = "/posts/"
#   weight = 40

[[main]]
  name = "Справочный центр"
  url = "/center/"
  weight = 50

[[main]]
  name = "Публикации"
  url = "/publication/"
  weight = 70

[[main]]
  name = "Проекты"
  url = "/project/"
  weight = 80

# [[main]]
#   name = "Контакты"
#   url = "/contact/"
#   weight = 90